server:
  port: 9090
  host: "0.0.0.0"
  endpoint: "/metrics"
  health: "/admin/health"

pinger:
  debug: true
  interval: 10
  metric-name: "pinger_metrics"
  hosts:
    - "https://en.wikipedia.org/"
    - "https://www.facebook.com"
    - "https://www.google.com"