---
kind: Service
apiVersion: v1
metadata:
  name: google-test-prometheus
  namespace: http-uptime
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: google-test
    app.kubernetes.io/managed-by: hand
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: google-test
